/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#5c647a",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "inverse-surface": "#213145",
        "background": "#f8f9ff",
        "on-secondary-fixed": "#131b2e",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-low": "#eff4ff",
        "surface": "#f8f9ff",
        "secondary-fixed": "#dae2fd",
        "surface-variant": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-tertiary-fixed-variant": "#444749",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#6b6e70",
        "surface-bright": "#f8f9ff",
        "on-tertiary-container": "#eff1f3",
        "surface-container-high": "#dce9ff",
        "secondary": "#565e74",
        "on-tertiary-fixed": "#191c1e",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-primary": "#ffffff",
        "surface-dim": "#cbdbf5",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "inverse-primary": "#b4c5ff",
        "secondary-container": "#dae2fd",
        "surface-tint": "#0053db",
        "on-primary-fixed-variant": "#003ea8",
        "on-surface-variant": "#434655",
        "primary-fixed": "#dbe1ff",
        "surface-container": "#e5eeff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#b4c5ff",
        "tertiary-fixed": "#e0e3e5",
        "on-primary-fixed": "#00174b",
        "surface-container-highest": "#d3e4fe",
        "outline-variant": "#c3c6d7",
        "primary-container": "#2563eb",
        "on-background": "#0b1c30",
        "primary": "#004ac6",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary": "#525657",
        "secondary-fixed-dim": "#bec6e0",
        "on-secondary": "#ffffff",
        "on-primary-container": "#eeefff",
        "outline": "#737686"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-gap-sm": "0.5rem",
        "stack-gap-md": "1rem",
        "stack-gap-lg": "1.5rem",
        "grid-gutter": "1rem",
        "container-padding": "1.25rem"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "body-sm": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "body-lg": ["Inter"]
      },
    },
  },
  plugins: [],
}
